In [1]:
import torch

/gel/usr/akath/.conda/envs/swin/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
img = torch.arange(8*8).reshape(8,8)

In [3]:
H, W = img.shape

In [4]:
B = 1
C =1

# window original swin

In [23]:
window_size = 2

In [24]:
x = img.view(1, 8 // window_size, window_size, 8 // window_size, window_size, 1)

In [25]:
windows = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(-1, window_size, window_size, 1)

In [26]:
img

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]])

In [27]:
B = int(windows.shape[0] / (H * W / window_size / window_size))
x = windows.view(B, H // window_size, W // window_size, window_size, window_size, -1)
x = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(B, H, W, -1)

In [28]:
x0 = x[:, 0::2, 0::2, :]  # B H/2 W/2 C
x1 = x[:, 1::2, 0::2, :]  # B H/2 W/2 C
x2 = x[:, 0::2, 1::2, :]  # B H/2 W/2 C
x3 = x[:, 1::2, 1::2, :]  # B H/2 W/2 C

In [29]:
x0

tensor([[[[ 0],
          [ 2],
          [ 4],
          [ 6]],

         [[16],
          [18],
          [20],
          [22]],

         [[32],
          [34],
          [36],
          [38]],

         [[48],
          [50],
          [52],
          [54]]]])

In [205]:
x = torch.cat([x0, x1, x2, x3], -1)

In [245]:
x = x.view(B, -1, 4 * 1)

In [249]:
x[0]

tensor([[ 0,  8,  1,  9],
        [ 2, 10,  3, 11],
        [ 4, 12,  5, 13],
        [ 6, 14,  7, 15],
        [16, 24, 17, 25],
        [18, 26, 19, 27],
        [20, 28, 21, 29],
        [22, 30, 23, 31],
        [32, 40, 33, 41],
        [34, 42, 35, 43],
        [36, 44, 37, 45],
        [38, 46, 39, 47],
        [48, 56, 49, 57],
        [50, 58, 51, 59],
        [52, 60, 53, 61],
        [54, 62, 55, 63]])

In [210]:
img

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]])

# merging swin along patch

In [5]:
x_ = img.view(1, H // 1, 1, W // 4, 4, 1)

In [6]:
windows_ = x_.permute(0, 1, 3, 2, 4, 5).contiguous().view(-1, 4, 1, 1)

In [7]:
windows_

tensor([[[[ 0]],

         [[ 1]],

         [[ 2]],

         [[ 3]]],


        [[[ 4]],

         [[ 5]],

         [[ 6]],

         [[ 7]]],


        [[[ 8]],

         [[ 9]],

         [[10]],

         [[11]]],


        [[[12]],

         [[13]],

         [[14]],

         [[15]]],


        [[[16]],

         [[17]],

         [[18]],

         [[19]]],


        [[[20]],

         [[21]],

         [[22]],

         [[23]]],


        [[[24]],

         [[25]],

         [[26]],

         [[27]]],


        [[[28]],

         [[29]],

         [[30]],

         [[31]]],


        [[[32]],

         [[33]],

         [[34]],

         [[35]]],


        [[[36]],

         [[37]],

         [[38]],

         [[39]]],


        [[[40]],

         [[41]],

         [[42]],

         [[43]]],


        [[[44]],

         [[45]],

         [[46]],

         [[47]]],


        [[[48]],

         [[49]],

         [[50]],

         [[51]]],


        [[[52]],

         [[53]],

  

In [8]:
B = int(windows_.shape[0] / (H * W / 4 / 1))
x_ = windows_.view(B, H // 1, W // 4, 1, 4, -1)
x_ = x_.permute(0, 1, 3, 2, 4, 5).contiguous().view(B, H, W, -1)
x_[0, :, :, 0]

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]])

In [15]:
x_0 = x_[:, :, 0::4, :].reshape(B, H//1, W//4, 1)  # B H/2 W/2 C
x_1 = x_[:, :, 1::4, :].reshape(B, H//1, W//4, 1)
x_2 = x_[:, :, 2::4, :].reshape(B, H//1, W//4, 1)
x_3 = x_[:, :, 3::4, :].reshape(B, H//1, W//4, 1)

In [10]:
z = x_[:, :, 0::4, :][:, :4, :, :]
o = x_[:, :, 0::4, :][:, 4:, :, :].flip(1)

In [16]:
results = torch.cat([x_0, x_1, x_2, x_3], -1)

In [26]:
results

torch.Size([1, 8, 2, 4])

In [20]:
t = torch.cat((x_0[:, :4, :, :], x_1[:, :4, :, :], x_2[:, :4, :, :], x_3[:, :4, :, :]), -1)
t_ = torch.cat((x_0[:, 4:, :, :].flip(1), x_1[:, 4:, :, :].flip(1), x_2[:, 4:, :, :].flip(1), x_3[:, 4:, :, :].flip(1)), -1)

In [25]:
t, t_

(tensor([[[[ 0,  1,  2,  3],
           [ 4,  5,  6,  7]],
 
          [[ 8,  9, 10, 11],
           [12, 13, 14, 15]],
 
          [[16, 17, 18, 19],
           [20, 21, 22, 23]],
 
          [[24, 25, 26, 27],
           [28, 29, 30, 31]]]]),
 tensor([[[[56, 57, 58, 59],
           [60, 61, 62, 63]],
 
          [[48, 49, 50, 51],
           [52, 53, 54, 55]],
 
          [[40, 41, 42, 43],
           [44, 45, 46, 47]],
 
          [[32, 33, 34, 35],
           [36, 37, 38, 39]]]]))

In [83]:
results = torch.empty(B, H//1, W//4, 4*1)
results[:, 0::2, :, :] = t
results[:, 1::2, :, :] = t_

In [84]:
results

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.]],

         [[56., 57., 58., 59.],
          [60., 61., 62., 63.]],

         [[ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[48., 49., 50., 51.],
          [52., 53., 54., 55.]],

         [[16., 17., 18., 19.],
          [20., 21., 22., 23.]],

         [[40., 41., 42., 43.],
          [44., 45., 46., 47.]],

         [[24., 25., 26., 27.],
          [28., 29., 30., 31.]],

         [[32., 33., 34., 35.],
          [36., 37., 38., 39.]]]])

In [61]:
x = results.view(B, -1, 4 * 1)

In [72]:
x = torch.cat([x_0_0, x_1_0, x_2_0, x_3_0], -1)

In [73]:
x_ = x_.view(B, -1, 4 * 1)

In [76]:
x_[0, :32]

tensor([[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31],
        [ 32,  33,  34,  35],
        [ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47],
        [ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63],
        [ 64,  65,  66,  67],
        [ 68,  69,  70,  71],
        [ 72,  73,  74,  75],
        [ 76,  77,  78,  79],
        [ 80,  81,  82,  83],
        [ 84,  85,  86,  87],
        [ 88,  89,  90,  91],
        [ 92,  93,  94,  95],
        [ 96,  97,  98,  99],
        [100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111],
        [112, 113, 114, 115],
        [116, 117, 118, 119],
        [120, 121, 122, 123],
        [124, 125, 126, 127]])

In [40]:
import torch.nn as nn

In [41]:
reduction = nn.Linear(4 * 1, 2 * 1, bias=False)

In [43]:
x_ = reduction(x.float())

In [45]:
x_

torch.Size([1, 256, 2])

In [49]:
x_1 = x_.view(1, 16, 16, 2)

In [50]:
x_1.shape

torch.Size([1, 16, 16, 2])

In [51]:
x_1[0, :, :, 0]

tensor([[-4.4765e-02, -2.0975e+00, -4.1503e+00, -6.2031e+00, -8.2558e+00,
         -1.0309e+01, -1.2361e+01, -1.4414e+01, -5.0913e+02, -5.1118e+02,
         -5.1324e+02, -5.1529e+02, -5.1734e+02, -5.1939e+02, -5.2145e+02,
         -5.2350e+02],
        [-1.6467e+01, -1.8520e+01, -2.0572e+01, -2.2625e+01, -2.4678e+01,
         -2.6731e+01, -2.8783e+01, -3.0836e+01, -4.9271e+02, -4.9476e+02,
         -4.9681e+02, -4.9887e+02, -5.0092e+02, -5.0297e+02, -5.0503e+02,
         -5.0708e+02],
        [-3.2889e+01, -3.4942e+01, -3.6995e+01, -3.9047e+01, -4.1100e+01,
         -4.3153e+01, -4.5206e+01, -4.7258e+01, -4.7629e+02, -4.7834e+02,
         -4.8039e+02, -4.8244e+02, -4.8450e+02, -4.8655e+02, -4.8860e+02,
         -4.9066e+02],
        [-4.9311e+01, -5.1364e+01, -5.3417e+01, -5.5469e+01, -5.7522e+01,
         -5.9575e+01, -6.1628e+01, -6.3681e+01, -4.5986e+02, -4.6192e+02,
         -4.6397e+02, -4.6602e+02, -4.6808e+02, -4.7013e+02, -4.7218e+02,
         -4.7423e+02],
        [-6.5733e+01

In [282]:
avgpool = nn.AdaptiveAvgPool1d(1)
x_ = avgpool(x_.transpose(1, 2))  # B C 1

In [287]:
x = torch.flatten(x_, 1)


In [288]:
x

tensor([[ -2.2822, -16.3735]], grad_fn=<ViewBackward>)

# Testing

In [16]:
import torch 
x_ = torch.arange(64).reshape(8,8)

In [63]:
x_0_0 = x_[:, 0::4].reshape(2, 4, 2)[0]  # B H/2 W/2 C
x_0_1 = x_[:, 0::4].reshape(2, 4, 2)[1].flip(0)  # B H/2 W/2 C
x_1_0 = x_[:, 1::4].reshape(2, 4, 2)[0]
x_1_1 = x_[:, 1::4].reshape(2, 4, 2)[1].flip(0)# B H/2 W/2 C
x_2_0 = x_[:, 2::4].reshape(2, 4, 2)[0]
x_2_1 = x_[:, 2::4].reshape(2, 4, 2)[1].flip(0)
x_3_0 = x_[:, 3::4].reshape(2, 4, 2)[0]# B H/2 W/2 C
x_3_1 = x_[:, 3::4].reshape(2, 4, 2)[1].flip(0)  # B H/2 W/2 C

In [64]:
t = torch.cat((x_0_0.reshape(4, 2, 1), x_1_0.reshape(4, 2, 1), x_2_0.reshape(4, 2, 1), x_3_0.reshape(4, 2, 1)), -1)
t_ = torch.cat((x_0_1.reshape(4, 2, 1), x_1_1.reshape(4, 2, 1), x_2_1.reshape(4, 2, 1), x_3_1.reshape(4, 2, 1)), -1)

In [68]:
results = torch.empty(8, 2, 4)

In [69]:
results[0::2, :, :] = t
results[1::2, :, :] = t_

In [70]:
results

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.]],

        [[56., 57., 58., 59.],
         [60., 61., 62., 63.]],

        [[ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]],

        [[48., 49., 50., 51.],
         [52., 53., 54., 55.]],

        [[16., 17., 18., 19.],
         [20., 21., 22., 23.]],

        [[40., 41., 42., 43.],
         [44., 45., 46., 47.]],

        [[24., 25., 26., 27.],
         [28., 29., 30., 31.]],

        [[32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [45]:
x_0_1 = t[0, :, :]
x_0_2 = t[1, :, :]

In [49]:
x_0_1, x_0_2.flip(0)

(tensor([[ 0,  4],
         [ 8, 12],
         [16, 20],
         [24, 28]]),
 tensor([[56, 60],
         [48, 52],
         [40, 44],
         [32, 36]]))

In [50]:
x_

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]])