In [272]:
import torch
from torchvision.utils import save_image
from PIL import Image, ImageOps
import numpy as np 
from torchvision import transforms
import wandb
img = torch.arange(10*10).reshape(10,10)
result = np.zeros((21,21))

In [324]:
import torch
from torchvision.utils import save_image
from PIL import Image, ImageOps
import numpy as np 
from torchvision import transforms
import wandb

t = transforms.ToPILImage()
res=1024

cartesian = torch.cartesian_prod(
    torch.linspace(-1.414, 1.414, res),
    torch.linspace(1.414, -1.414, res)
).reshape(res, res, 2).transpose(2, 1).transpose(1, 0).transpose(1, 2)
radius = cartesian.norm(dim=0)
y = cartesian[1]
x = cartesian[0]
theta = torch.atan2(cartesian[1], cartesian[0])
image = torch.randn(res, res, 3)
mask = (radius >0.75) & (radius < 1)
mask1= (radius >0.5) & (radius < 0.75)
mask2= (radius >0.25) & (radius < 5)
mask3= (radius >0.0) & (radius < 0.25)
mask = torch.nn.functional.interpolate(mask.unsqueeze(0).unsqueeze(0) * 1.0, (10), mode="area")
mask1 = torch.nn.functional.interpolate(mask1.unsqueeze(0).unsqueeze(0) * 1.0, (10), mode="area")
mask2 = torch.nn.functional.interpolate(mask2.unsqueeze(0).unsqueeze(0) * 1.0, (10), mode="area")
mask3 = torch.nn.functional.interpolate(mask3.unsqueeze(0).unsqueeze(0) * 1.0, (10), mode="area")

im = img*mask
im1 = img*mask1
im2 = img*mask2
im3 = img*mask3

# wandb.log({"masks" : [wandb.Image(image) for image in lst]})

# wandb.log({"segments" : [wandb.Image(image) for image in img]})
# wandb.log({"original image" : wandb.Image(im)})


In [210]:
radius = [1, 2, 3,4]
theta= [] 
for i in range(16):
    t = 0 + np.pi/8*i
    theta.append(t)

In [245]:
img.shape

(8, 8)

In [257]:
i = 0
j = 0
for r in radius:
    for th in theta:
        x = r*np.cos(th)
        y = r*np.sin(th)
        if x>0 and x <1e-3:
            x = 0
        elif y>0 and y <1e-3:
            y = 0
        if x<0 and x > -1e-3:
            x = 0
        elif y<0 and y > -1e-3:
            y = 0
        x = int(x*5)
        y = int(y*5)
        result[x][y] = img[j]
        j = j +1


In [260]:
result

array([[ 0., 60.,  0.,  0.,  0.,  4., 44.,  0.,  0.,  0., 20., 28.,  0.,
         0.,  0., 36., 12.,  0.,  0.,  0., 52.],
       [56.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0., 13.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  0.,  0.,  0., 55.,  0., 19.,  0.,  0., 29.,
         0., 57.,  0.,  0.,  0., 14.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0., 15.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 45.,  0.,  0.,  0.,  0.,
        35.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [40.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 61.,  0.,  0.,  0., 58.,  0.,  0.,  0.,  0.,  0.,
         0., 54.,  0.,  0.,  0., 51.,  0.,  0.],
       [ 0.,  0.,  0.,  

In [326]:
A = np.array(im[0, 0])
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
#         import pdb;pdb.set_trace()
        print(float("{0:.1f}".format(A[i][j])))
        A[i][j] = float("{0:.1f}".format(A[i][j]))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [323]:
im.shape

torch.Size([1, 1, 10, 10])

In [320]:
im

tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]])

In [267]:
32*np.sqrt(2)

45.254833995939045

In [294]:
im

tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]])